version: '3.3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./basco-root:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - magento-network

  php-fpm:
    image: php:8.2.19-fpm
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./basco-root:/var/www/html
    networks:
      - magento-network

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./es_data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      networks:
        - magento-network
      
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_Amazon52Doom54Shyest13Light93
      MYSQL_DATABASE: af5d0fe8_323220
      MYSQL_USER: af5d0fe8_323220
      MYSQL_PASSWORD: Amazon52Doom54Shyest13Light93
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
    - 3307:3306
    networks:
      - magento-network

networks:
  magento-network:
      driver: bridge

